build_hooks_bitbucket.settings:
  type: config_object
  label: 'Build hooks bitbucket settings'
  mapping:
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'

frontend_environment.settings.bitbucket:
  type: build_hooks.frontend_environment.plugin_settings
  mapping:
    repo:
      type: mapping
      mapping:
        workspace:
          type: string
          label: 'Repo Workspace'
        slug:
          type: string
          label: 'Repo Slug'
    ref:
      type: mapping
      mapping:
        type:
          type: string
          label: 'Ref type'
        name:
          type: string
          label: 'Ref name'
    selector:
      type: mapping
      mapping:
        type:
          type: string
          label: 'Pipeline type'
        name:
          type: string
          label: 'Pipeline name'
