build_hooks_github.settings:
  type: config_object
  label: 'Github Build hooks settings'
  mapping:
    github_access_token:
      type: string
      label: 'Github Access Token'

frontend_environment.settings.github:
  type: build_hooks.frontend_environment.plugin_settings
  mapping:
    branch:
      type: string
      label: 'Branch'
    build_hook_url:
      type: string
      label: 'Build hook URL'
