build_hooks_netlify.settings:
  type: config_object
  label: 'Netlify Build hooks settings'
  mapping:
    netlify_api_key:
      type: string
      label: 'API key'

frontend_environment.settings.netlify:
  type: build_hooks.frontend_environment.plugin_settings
  mapping:
    branch:
      type: string
      label: 'Branch'
    build_hook_url:
      type: string
      label: 'Build hook URL'
    api_id:
      type: string
      label: 'API ID'
