build_hooks.frontend_environment.*:
  type: config_entity
  label: 'Frontend environment config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    provider:
      type: string
      label: 'Provider'
    plugin:
      type: string
      label: 'Plugin'
    deployment_strategy:
      type: string
      label: 'Deployment strategy'
    url:
      type: string
      label: 'Url'
    weight:
      type: integer
      label: 'Weight'
    settings:
      type: frontend_environment.settings.[%parent.plugin]

build_hooks.settings:
  type: config_object
  label: 'Build hooks settings'
  mapping:
    logging:
      type: mapping
      label: 'Logging settings'
      mapping:
        entity_types:
          label: 'Entity types'
          type: sequence
          sequence:
            type: string

build_hooks.frontend_environment.plugin_settings:
  type: mapping
  label: 'Plugin settings'
  mapping:
    id:
      type: string
      label: 'Plugin ID'
    label:
      type: string
      label: 'Plugin Label'
    provider:
      type: string
      label: 'Provider'

frontend_environment.settings.generic:
  type: build_hooks.frontend_environment.plugin_settings
  mapping:
    build_hook_url:
      type: string
      label: 'Build hook URL'
