_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 38fe2bf4-deca-4bf5-b36f-fc5ebfbdb358
name: 'U-M Library Design System CMS'
mail: library-design-system-team@umich.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/4
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
