build_hooks_circleci.settings:
  type: config_object
  label: 'Circle CI Build hooks settings'
  mapping:
    circleci_api_key:
      type: string
      label: 'API key'

frontend_environment.settings.circleci:
  type: build_hooks.frontend_environment.plugin_settings
  mapping:
    branch:
      type: string
      label: 'Branch'
    project:
      type: string
      label: 'Project'

frontend_environment.settings.circleciv2:
  type: build_hooks.frontend_environment.plugin_settings
  mapping:
    reference:
      type: string
      label: 'Branch or Tag'
    project:
      type: string
      label: 'Project'
    type:
      type: string
      label: 'Type'
    token:
      type: string
      label: 'Token'
    parameters:
      type: sequence
      label: 'Parameters'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
            label: 'Parameter name'
          type:
            type: string
            label: 'Type'
          value:
            type: '[%parent.type]'
            label: 'Parameter value'
