name: Build drupal on push to main

on:
  push:
    branches:
      - main
    paths: 
      - "drupal/**"

env:
  IMAGE_NAME: design-system-cms

jobs:
  build-drupal:
    name: Build ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone latest repository
      uses: actions/checkout@v3
    - name: Log into Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: drupal/.
        file: drupal/Dockerfile.prod
        push: true
        tags: | 
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ github.sha }}
